version: '3.7'

services:
  vrising:
    container_name: v-rising
    #image: mephi00/v-rising-wine
    build: .
    volumes:
      - type: bind
        source: ./saves
        target: /saves
    env_file:
      - path: ./.env
        required: true
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
